repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--config-file=./pyproject.toml]

  # - repo: local
  #   hooks:

  #     - id: ruff-format
  #       name: ruff format
  #       language: system
  #       entry: make fmt
  #       types: [python]
  #       require_serial: true

  #     - id: ruff-lint-fix
  #       name: ruff lint fix
  #       language: system
  #       entry: make lint-fix
  #       types: [python]
  #       require_serial: true

  #     - id: mypy-type-check
  #       name: mypy type check
  #       language: system
  #       entry: make typechk
  #       types: [python]
  #       require_serial: true
